name: ioe_app
description: "IOE Frontend App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.8
  mobile_scanner: ^5.0.0
  uuid: ^4.5.1
  web: ^1.1.1
  pdf: ^3.11.0
  printing: ^5.12.0
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
